---
clair_scan_params: &clair_scan_params
  CLAIR_HOST: {{clair_addr}}
  CLAIR_IMAGE: {{clair_image}}
  HARBOR_USERNAME: {{harbor_username}}
  HARBOR_PASSWORD: {{harbor_password}}

notary_sign_params: &notary_sign_params
  HARBOR_USERNAME: {{harbor_username}}
  HARBOR_URL: {{harbor_url}}
  HARBOR_IMAGE: {{harbor_image}}
  HARBOR_PASSWORD: {{harbor_password}}
  HARBOR_CA_CERT: {{harbor_ca_cert}}
  HARBOR_CA_KEY: {{harbor_ca_key}}
  NOTARY_FILE_1: {{notary_file_1}}
  NOTARY_KEY_1: {{notary_key_1}}
  NOTARY_FILE_2: {{notary_file_2}}
  NOTARY_KEY_2: {{notary_key_2}}
groups:

- name: Image-Pipeline
  jobs:
  - build-docker-image
  - cve-scan-harbor-image
  - push-harbor-image

resources:
- name: git-spring1-ci
  type: git
  source:
    uri: https://github.com/prasenforu/concourse-ci
    branch: master

- name: git-go-http
  type: git
  source:
    uri: https://github.com/prasenforu/dockerapp
    branch: master

- name: harbor-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: {{harbor_username}}
    password: {{harbor_password}}
    repository: {{harbor_repository}}

jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-go-http
    trigger: true
  - put: harbor-image
    params:
      build: git-go-http

- name: cve-scan-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [build-docker-image]
      trigger: true
  - task: clair-scan-image
    file: git-spring1-ci/tasks/clair-scan-image/task.yml
    params: *clair_scan_params

- name: push-harbor-image
  plan:
  - aggregate:
    - get: git-spring1-ci
    - get: harbor-image
      passed: [cve-scan-harbor-image]
      trigger: false
  - task: notary-sign-image
    privileged: true
    file: git-spring1-ci/tasks/notary-sign-image/task.yml
    params: *notary_sign_params
